// M11 standard pass-protection and pocket visual/structural gate.
// Usage: node tools/pocket_protection_probe.mjs [shot.png]
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root=join(dirname(fileURLToPath(import.meta.url)),'..'),shot=process.argv[2]||join(root,'_pocket-protection.png');
const tmp=mkdtempSync(join(tmpdir(),'wsppocket-')),entry=join(tmp,'entry.js'),bundle=join(tmp,'bundle.js');
writeFileSync(entry,`import { spriteMarkup } from ${JSON.stringify(join(root,'js/ui/sprite.js').replace(/\\/g,'/'))};window.__spriteMarkup=spriteMarkup;`);
const esbuild=process.platform==='win32'?join(root,'node_modules/@esbuild/win32-x64/esbuild.exe'):join(root,'node_modules/esbuild/bin/esbuild');execFileSync(esbuild,[entry,'--bundle','--format=iife',`--outfile=${bundle}`],{stdio:'pipe'});
const css=readFileSync(join(root,'style.css'),'utf8'),js=readFileSync(bundle,'utf8');
const html=`<!doctype html><meta charset="utf-8"><style>${css}
html,body{margin:0;background:#082719}#watch-board{display:block;width:1600px;height:1000px}.pk-title{fill:#ffd34d;font:900 2.2px monospace;text-anchor:middle}.pk-sub{fill:#a9c0b2;font:800 1px monospace;text-anchor:middle}.pk-cell .wsp-tag{display:none}.pk-rule{stroke:#214b36;stroke-width:.2}
</style><svg id="watch-board" class="watch-sprites watch-in-play watch-pass-pocket" viewBox="0 0 200 125"></svg><script>${js}<\/script><script>
const svg=document.getElementById('watch-board');svg.style.setProperty('--wsp-off','#f2ead8');svg.style.setProperty('--wsp-off-hl','#dda919');svg.style.setProperty('--wsp-def','#982c40');svg.style.setProperty('--wsp-def-hl','#f2ead8');
const actor=(team,id,pos,face,cls,x,y)=>'<g class="pk-cell wp-actor wp-team-'+team+' wsp-face-'+face+' '+cls+'" data-case="'+id+'" transform="translate('+x+','+y+') scale(4)">'+window.__spriteMarkup({id:team+'-'+id,team,label:pos,pos,grp:pos,qb:pos==='QB'},face)+'</g>';const fams=[['EDGE','edge','bend'],['POWER','power','bull'],['COUNTER','counter','counter']];let out='<line class="pk-rule" x1="4" x2="196" y1="52" y2="52"/>';
fams.forEach((f,i)=>{const x=35+i*65,y=38;out+='<text class="pk-title" x="'+x+'" y="6">'+f[0]+' ANCHOR</text><text class="pk-sub" x="'+x+'" y="8.5">SETTER HOLDS LEVERAGE</text>';out+=actor('off','anchor-'+f[1],'OL','e','wp-pass-set wp-pass-anchor wp-pass-'+f[1],x-4.5,y)+actor('def','fit-'+f[1],'DL','w','wp-pass-engaged wp-pass-'+f[1],x+4.5,y);});
fams.forEach((f,i)=>{const x=35+i*65,y=86;out+='<text class="pk-title" x="'+x+'" y="57">'+f[0]+' LOSS</text><text class="pk-sub" x="'+x+'" y="59.5">RUSHER CLEARS THE GATE</text>';out+=actor('off','lost-'+f[1],'OL','e','wp-pass-set wp-pass-lost wp-pass-'+f[1]+' wp-shed wp-shed-'+f[2],x-4.5,y)+actor('def','win-'+f[1],'DL','w','wp-pass-engaged wp-pass-won wp-pass-'+f[1]+' wp-rushing wp-rush-win wp-rush-'+f[2],x+4.5,y);});
out+='<text class="pk-title" x="100" y="111">QUARTERBACK POCKET</text><text class="pk-sub" x="100" y="114">BALL SECURE, BASE ALIVE</text>'+actor('off','qb-pocket','QB','e','wp-qb wp-pocket-qb wp-near-ball wsp-still',100,123);svg.innerHTML=out;
const anim=n=>getComputedStyle(n).animationName,anchors=[...svg.querySelectorAll('[data-case^="anchor-"]')],fits=[...svg.querySelectorAll('[data-case^="fit-"]')],losses=[...svg.querySelectorAll('[data-case^="lost-"]')],wins=[...svg.querySelectorAll('[data-case^="win-"]')];window.__report={actors:svg.querySelectorAll('.wp-actor').length,anchors:anchors.map(n=>anim(n.querySelector('.wsp-shell'))),fits:fits.map(n=>anim(n.querySelector('.wsp-shell'))),losses:losses.map(n=>anim(n.querySelector('.wsp-shell'))),wins:wins.map(n=>anim(n.querySelector('.wsp-shell'))),hands:anchors.flatMap(n=>[...n.querySelectorAll('.wsp-pose-block .wsp-limb')].map(anim)),feet:anchors.flatMap(n=>[...n.querySelectorAll('.wsp-sd-thigh')].map(anim)),qb:anim(svg.querySelector('[data-case="qb-pocket"] .wsp-shell')),blockPoses:[...svg.querySelectorAll('.wp-pass-set .wsp-pose-block,.wp-pass-engaged .wsp-pose-block')].every(n=>getComputedStyle(n).display!=='none')};
<\/script>`;
const pagePath=join(tmp,'pocket.html');writeFileSync(pagePath,html);const {chromium}=await import(pathToFileURL(join(root,'node_modules/playwright/index.mjs')).href);const browser=await chromium.launch({executablePath:process.env.PW_CHROMIUM||undefined});const page=await browser.newPage({viewport:{width:1600,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('file://'+pagePath);await page.waitForTimeout(220);const report=await page.evaluate('window.__report');await page.screenshot({path:shot});await browser.close();
let pass=true;const check=(n,ok,d='')=>{console.log((ok?'PASS ':'FAIL ')+n+(d?'  ['+d+']':''));if(!ok)pass=false};const uniq=a=>new Set(a.filter(n=>n&&n!=='none'));
check('pageerrors 0',errors.length===0,errors.join(' | ').slice(0,260));check('all 13 pocket actors render',report.actors===13,'count='+report.actors);check('edge, power and counter anchors differ',uniq(report.anchors).size===3,report.anchors.join(','));check('three rusher fit families differ',uniq(report.fits).size===3,report.fits.join(','));check('three lost-leverage finishes differ',uniq(report.losses).size===3,report.losses.join(','));check('rusher wins retain three authored moves',uniq(report.wins).size===3,report.wins.join(','));check('pass setters use authored block hands',uniq(report.hands).size>=5,'unique='+uniq(report.hands).size);check('kick-slide, anchor and square footwork differ',uniq(report.feet).size>=6,'unique='+uniq(report.feet).size);check('pass-set and engaged bodies show contact pose',report.blockPoses);check('quarterback owns a live pocket base',report.qb==='wsp-m11-qb-pocket',report.qb);console.log('shot: '+shot);process.exit(pass?0:1);
