// M13 end-to-end quarterback mechanics gate.
// Usage: node tools/qb_live_probe.mjs <built.html> [shot.png]
import { chromium } from "playwright";
const target=process.argv[2],shot=process.argv[3]||"_qb-live.png";if(!target){console.error("usage: node tools/qb_live_probe.mjs <built.html> [shot.png]");process.exit(1)}
const browser=await chromium.launch({executablePath:process.env.PW_CHROMIUM||undefined}),page=await browser.newPage({viewport:{width:1180,height:820}}),errors=[];page.on("pageerror",e=>errors.push(String(e)));await page.goto("file://"+target,{waitUntil:"load"});await page.waitForTimeout(800);await page.click("#btn-mm-playnow");await page.waitForTimeout(450);await page.click('[data-pn-star="home:6"]');await page.click('[data-pn-div="away:D3"]');await page.waitForTimeout(250);await page.click('[data-pn-star="away:1"]');await page.waitForTimeout(250);await page.click("#pn-start");
async function settle(maxMs=30000){const start=Date.now();while(Date.now()-start<maxMs){if(await page.locator('[data-cs-drill="quick"]').count())return true;for(const s of["#dc-ride","#dc-send","#watch-live-skip","#watch-continue"]){const n=page.locator(s);if(await n.count())await n.click().catch(()=>{})}await page.waitForTimeout(350)}return false}
let sheet=false,live=false,snap=false,drop=false,hitch=false,load=false,follow=false,family=false,pose=false,shotDone=false,leaked=false;
for(let attempt=0;attempt<3&&!(live&&snap&&drop&&load&&follow);attempt++){const ready=await settle();sheet||=ready;if(!ready)break;await page.click('[data-cs-drill="quick"]');await page.waitForTimeout(180);await page.locator("[data-cs-callconcept]").first().click();await page.waitForSelector("#watch-board",{timeout:20000});for(let frame=0;frame<220;frame++){const s=await page.evaluate(()=>{const b=document.querySelector("#watch-board"),q=b?.querySelector('[data-wpa="QB"]');return{live:b?.classList.contains("watch-qb-mechanics")||false,snap:q?.classList.contains("wp-qb-snap")||false,drop:q?.classList.contains("wp-qb-drop")||false,hitch:q?.classList.contains("wp-qb-hitch")||false,load:q?.classList.contains("wp-qb-load")||false,follow:q?.classList.contains("wp-qb-follow")||false,family:!!q&&[...q.classList].some(c=>/^wp-qb-(quick|three|five|playaction)$/.test(c)),pose:q?getComputedStyle(q.querySelector(".wsp-pose-throw")).display!=="none":false}});live||=s.live;snap||=s.snap;drop||=s.drop;hitch||=s.hitch;load||=s.load;follow||=s.follow;family||=s.family;pose||=s.follow&&s.pose;if(s.follow&&!shotDone){await page.screenshot({path:shot});shotDone=true}await page.waitForTimeout(20)}leaked||=await page.evaluate(()=>{const b=document.querySelector("#watch-board");return!b?.classList.contains("watch-qb-mechanics")&&!!b?.querySelector(".wp-qb-mechanics")})}
if(!shotDone)await page.screenshot({path:shot});await browser.close();let pass=true;const check=(n,ok,d="")=>{console.log((ok?"PASS ":"FAIL ")+n+(d?`  [${d}]`:""));if(!ok)pass=false};check("pageerrors 0",errors.length===0,errors.join(" | ").slice(0,260));check("passing call sheet reached",sheet);check("explicit quarterback mechanics window observed",live);check("snap security phase observed",snap);check("recorded drop family identified",family);check("dropback cadence observed",drop);check("set transitions into hitch or direct load",hitch||load,`hitch=${hitch} load=${load}`);check("arm load observed before release",load);check("follow-through observed after release",follow);check("follow-through retains throw pose",pose);check("quarterback mechanics clear after the play",!leaked);console.log("shot: "+shot);process.exit(pass?0:1);
