// M16 field-state integrity gate: two live possessions plus a forced punt.
// Usage: node tools/field_state_live_probe.mjs <built.html> [shot.png]
import { chromium } from "playwright";
const target=process.argv[2],shot=process.argv[3]||"_field-state-live.png";
if(!target){console.error("usage: node tools/field_state_live_probe.mjs <built.html> [shot.png]");process.exit(1)}
const browser=await chromium.launch({executablePath:process.env.PW_CHROMIUM||undefined}),page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on("pageerror",e=>errors.push(String(e)));await page.goto("file://"+target,{waitUntil:"load"});await page.waitForTimeout(700);await page.click("#btn-mm-playnow");await page.waitForTimeout(420);await page.click('[data-pn-mode="both"]');await page.click('[data-pn-star="home:3"]');await page.click('[data-pn-div="away:D3"]');await page.waitForTimeout(180);await page.click('[data-pn-star="away:3"]');await page.click("#pn-start");
async function settleSheet(maxMs=30000){const t0=Date.now();while(Date.now()-t0<maxMs){if(await page.locator('[data-cs-st-toggle]').count())return true;for(const s of['#dc-ride','#dc-send','#watch-live-skip','#watch-continue']){const n=page.locator(s);if(await n.count())await n.click().catch(()=>{})}await page.waitForTimeout(240)}return false}
async function callRunAndRead(){if(!await settleSheet())return null;const inside=page.locator('[data-cs-drill="inside"]');if(await inside.count())await inside.click();else await page.locator('[data-cs-drill]').first().click();await page.waitForTimeout(100);await page.locator('[data-cs-callconcept]').first().click();await page.waitForSelector('#watch-board[data-field-possession]:not([data-field-possession=""])',{timeout:15000});for(let i=0;i<90;i++){const s=await page.evaluate(()=>{const b=document.querySelector('#watch-board'),los=b?.querySelector('[data-wf-los]'),first=b?.querySelector('[data-wf-first]'),home=b?.querySelector('[data-wf-owner="home"] .wf-endzone'),away=b?.querySelector('[data-wf-owner="away"] .wf-endzone'),off=b?.querySelector('.wp-team-off'),vb=(b?.getAttribute('viewBox')||'').split(/\s+/).map(Number);return{possession:b?.dataset.fieldPossession||'',direction:b?.dataset.fieldDirection||'',arrow:b?.querySelector('.wf-drive-direction')?.dataset.wfDirection||'',los:los?Number(los.getAttribute('x1')):null,first:first?Number(first.getAttribute('x1')):null,homeX:home?Number(home.getAttribute('x')):null,awayX:away?Number(away.getAttribute('x')):null,face:off?[...off.classList].find(c=>c.startsWith('wsp-face-'))||'':'',bug:document.querySelector('#watch-bug')?.dataset.possession||'',presnap:b?.classList.contains('watch-presnap')||false,view:vb}});if(s.presnap&&s.first!=null&&s.face)return s;await page.waitForTimeout(12)}return null}
const first=await callRunAndRead();if(first?.possession==='away')await page.screenshot({path:shot});await settleSheet();
let puntStart='',puntChanged=false,puntBoard=false;
if(await page.locator('[data-cs-st-toggle]').count()){await page.click('[data-cs-st-toggle]');await page.waitForTimeout(80);await page.click('[data-cs-st="punt"]');for(let i=0;i<700;i++){const s=await page.evaluate(()=>({board:document.querySelector('#watch-board')?.classList.contains('watch-kick-punt')||false,field:document.querySelector('#watch-board')?.dataset.fieldPossession||'',bug:document.querySelector('#watch-bug')?.dataset.possession||''}));if(s.board){puntBoard=true;if(!puntStart)puntStart=s.field;if(s.bug&&s.bug!==puntStart){puntChanged=true;break}}await page.waitForTimeout(12)}}
const second=await callRunAndRead();if(!first?.possession||first.possession!=='away')await page.screenshot({path:shot});await browser.close();
let pass=true;const check=(n,ok,d="")=>{console.log((ok?"PASS ":"FAIL ")+n+(d?`  [${d}]`:""));if(!ok)pass=false};const valid=s=>s&&s.direction===(s.possession==='home'?'right':'left')&&s.arrow===s.direction&&s.los===31&&s.first!=null&&(s.direction==='right'?s.first>31:s.first<31)&&s.homeX<s.awayX&&s.face===(s.direction==='right'?'wsp-face-e':'wsp-face-w')&&s.bug===s.possession&&s.view.length===4;check("pageerrors 0",errors.length===0,errors.join(" | ").slice(0,260));check("first live possession has one coherent field state",valid(first),JSON.stringify(first));check("forced punt uses the recorded possession board",puntBoard&&!!puntStart,`board=${puntBoard} start=${puntStart}`);check("scorebug possession changes after the punt",puntChanged,`start=${puntStart} changed=${puntChanged}`);check("second live possession has one coherent field state",valid(second),JSON.stringify(second));check("both home and away possession directions are observed",first&&second&&first.possession!==second.possession,`${first?.possession||'none'} -> ${second?.possession||'none'}`);console.log("shot: "+shot);process.exit(pass?0:1);
