// M16 real-result kickoff orientation and team-role gate.
// Usage: node tools/kickoff_orientation_probe.mjs [shot.png]
import { chromium } from "playwright-core";
import http from "node:http";
import { readFile } from "node:fs/promises";
import { extname,join } from "node:path";
import { fileURLToPath } from "node:url";
const root=fileURLToPath(new URL("..",import.meta.url)),shot=process.argv[2]||join(root,"_kickoff-orientation.png"),mime={".html":"text/html",".js":"text/javascript",".css":"text/css",".json":"application/json",".png":"image/png"};
const server=http.createServer(async(req,res)=>{try{const rel=decodeURIComponent(req.url.split("?")[0]).replace(/^\/+/,"")||"index.html",body=await readFile(join(root,rel));res.writeHead(200,{"content-type":mime[extname(rel)]||"application/octet-stream"});res.end(body)}catch{res.writeHead(404);res.end("not found")}});await new Promise(r=>server.listen(0,r));
const browser=await chromium.launch({executablePath:process.env.PW_CHROMIUM||undefined}),page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on("pageerror",e=>errors.push(String(e)));await page.goto(`http://127.0.0.1:${server.address().port}/index.html`);await page.waitForTimeout(600);await page.click("#btn-mm-playnow");await page.waitForTimeout(350);await page.click('[data-pn-mode="watch"]');await page.click("#pn-start");await page.waitForTimeout(500);
const seeded=await page.evaluate(async()=>{const api=await import("./js/state.js"),t=api.state.pendingHalftime?.token;if(!t)return null;let found=null;for(const d of t.drives||[]){const p=(d.plays||[]).find(p=>p.type==="kickoff"&&!p.onside&&!p.touchback&&(p.retYds||0)>0&&!p.returnTD);if(p){found={d:{...d,plays:[p]},p};break}}if(!found){for(const d of t.drives||[]){const p=(d.plays||[]).find(p=>p.type==="kickoff"&&!p.onside);if(p){found={d:{...d,plays:[p]},p};break}}}if(!found)return null;t.drives=[found.d];t._watchedPlays=0;t.callMode=null;api.state._exhNonce=(api.state._exhNonce||0)+1;api.state.ui.liveWatch={stage:"halftime"};api.state.ui.showHalftime=false;api.rerender();return{possession:found.d.possession,touchback:!!found.p.touchback,retYds:found.p.retYds||0}});
let board=false,kTeam="",prTeam="",dir="",startX=null,flightX=null,shotDone=false;
for(let i=0;i<650;i++){const s=await page.evaluate(()=>{const b=document.querySelector("#watch-board"),ball=b?.querySelector("#wp-ball"),k=b?.querySelector('[data-wpk="K"]'),pr=b?.querySelector('[data-wpk="PR"]');return{board:b?.classList.contains("watch-kickoff")||false,dir:b?.dataset.fieldDirection||"",x:ball?Number((ball.getAttribute("transform")||"").match(/translate\(([-\d.]+)/)?.[1]):null,flight:ball?.classList.contains("wp-ball-kickoff")||false,k:k?[...k.classList].find(c=>c==="wp-team-off"||c==="wp-team-def")||"":"",pr:pr?[...pr.classList].find(c=>c==="wp-team-off"||c==="wp-team-def")||"":""}});if(s.board){board=true;dir=s.dir;kTeam||=s.k;prTeam||=s.pr;if(s.flight&&startX==null)startX=s.x;if(s.flight)flightX=s.x;if(!shotDone&&s.flight&&s.pr){await page.screenshot({path:shot});shotDone=true}}if(board&&startX!=null&&flightX!=null&&Math.abs(flightX-startX)>12)break;await page.waitForTimeout(12)}
if(!shotDone)await page.screenshot({path:shot});await browser.close();await new Promise(r=>server.close(r));let pass=true;const check=(n,ok,d="")=>{console.log((ok?"PASS ":"FAIL ")+n+(d?`  [${d}]`:""));if(!ok)pass=false};const expectedDir=seeded?.possession==="away"?"left":"right",travel=startX!=null&&flightX!=null?flightX-startX:null;check("pageerrors 0",errors.length===0,errors.join(" | ").slice(0,240));check("real simulated kickoff isolated",!!seeded,JSON.stringify(seeded));check("kickoff inherits receiving-drive direction",board&&dir===expectedDir,`board=${board} dir=${dir} expected=${expectedDir}`);check("kicker wears the non-possessing team",kTeam==="wp-team-def",kTeam);check("returner wears the possessing team when rendered",seeded?.touchback||prTeam==="wp-team-off",prTeam||"touchback");check("kick travels toward the receiver's own end",travel!=null&&(dir==="right"?travel<0:travel>0),`travel=${travel} dir=${dir}`);console.log("shot: "+shot);process.exit(pass?0:1);
