// M13 quarterback mechanics visual/structural gate.
// Usage: node tools/qb_mechanics_probe.mjs [shot.png]
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const root=join(dirname(fileURLToPath(import.meta.url)),".."),shot=process.argv[2]||join(root,"_qb-mechanics.png"),tmp=mkdtempSync(join(tmpdir(),"wspqb-")),entry=join(tmp,"entry.js"),bundle=join(tmp,"bundle.js");
writeFileSync(entry,`import { spriteMarkup } from ${JSON.stringify(join(root,"js/ui/sprite.js").replace(/\\/g,"/"))};window.__spriteMarkup=spriteMarkup;`);
const esbuild=process.platform==="win32"?join(root,"node_modules/@esbuild/win32-x64/esbuild.exe"):join(root,"node_modules/esbuild/bin/esbuild");execFileSync(esbuild,[entry,"--bundle","--format=iife",`--outfile=${bundle}`],{stdio:"pipe"});
const css=readFileSync(join(root,"style.css"),"utf8"),js=readFileSync(bundle,"utf8");
const html=`<!doctype html><meta charset="utf-8"><style>${css}html,body{margin:0;background:#071d18}#watch-board{display:block;width:1600px;height:1000px}.q-title{fill:#ffd34d;font:900 2px monospace;text-anchor:middle}.q-sub{fill:#a9c0b2;font:800 .85px monospace;text-anchor:middle}.q-cell .wsp-tag{display:none}.q-rule{stroke:#214b36;stroke-width:.2}</style><svg id="watch-board" class="watch-sprites watch-in-play watch-qb-mechanics" viewBox="0 0 200 125"></svg><script>${js}<\/script><script>
const svg=document.getElementById('watch-board');svg.style.setProperty('--wsp-off','#f2ead8');svg.style.setProperty('--wsp-off-hl','#dda919');const actor=(id,cls,x,y)=>'<g class="q-cell wp-actor wp-team-off wp-qb wsp-face-e '+cls+'" data-case="'+id+'" transform="translate('+x+','+y+') scale(4)">'+window.__spriteMarkup({id:'qb-'+id,team:'off',label:'QB',pos:'QB',grp:'QB',qb:true},'e')+'</g>';
const phases=[['SNAP SECURE','wp-qb-mechanics wp-qb-three wp-qb-snap'],['PLAY-ACTION','wp-qb-mechanics wp-qb-playaction wp-qb-mesh'],['QUICK SET','wp-qb-mechanics wp-qb-quick wp-qb-drop'],['THREE STEP','wp-qb-mechanics wp-qb-three wp-qb-drop'],['FIVE STEP','wp-qb-mechanics wp-qb-five wp-qb-drop'],['HITCH','wp-qb-mechanics wp-qb-three wp-qb-hitch'],['PRESSURE RESET','wp-qb-mechanics wp-qb-three wp-qb-reset'],['ARM LOAD','wp-qb-mechanics wp-qb-three wp-qb-load wp-throwing'],['FOLLOW THROUGH','wp-qb-mechanics wp-qb-three wp-qb-follow']];let out='<line class="q-rule" x1="4" x2="196" y1="62" y2="62"/>';phases.forEach((p,i)=>{const top=i<5,x=20+(i%5)*40,y=top?47:112;out+='<text class="q-title" x="'+x+'" y="'+(top?7:69)+'">'+p[0]+'</text><text class="q-sub" x="'+x+'" y="'+(top?9.5:71.5)+'">QB MECHANICS</text>'+actor('phase-'+i,p[1],x,y)});svg.innerHTML=out;
const anim=n=>getComputedStyle(n).animationName,cases=[...svg.querySelectorAll('[data-case]')];window.__report={actors:cases.length,shell:cases.map(n=>anim(n.querySelector('.wsp-shell'))),dropFeet:cases.slice(2,5).flatMap(n=>[...n.querySelectorAll('.wsp-sd-thigh')].map(anim)),hitchFeet:[...cases[5].querySelectorAll('.wsp-sd-thigh')].map(anim),snapHands:[...cases[0].querySelectorAll('.wsp-carry-arm-l,.wsp-carry-arm-r,.wsp-sd-carry-arm')].map(anim),meshHands:[...cases[1].querySelectorAll('.wsp-carry-arm-l,.wsp-sd-carry-arm')].map(anim),load:[...cases[7].querySelectorAll('.wsp-throw-arm,.wsp-sd-throw-arm')].map(anim),follow:[...cases[8].querySelectorAll('.wsp-throw-arm,.wsp-sd-throw-arm,.wsp-throw-guide,.wsp-sd-guide-arm')].map(anim),followPose:getComputedStyle(cases[8].querySelector('.wsp-pose-throw')).display};<\/script>`;
const pagePath=join(tmp,"qb.html");writeFileSync(pagePath,html);const {chromium}=await import(pathToFileURL(join(root,"node_modules/playwright/index.mjs")).href),browser=await chromium.launch({executablePath:process.env.PW_CHROMIUM||undefined}),page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];page.on("pageerror",e=>errors.push(String(e)));await page.goto("file://"+pagePath);await page.waitForTimeout(260);const report=await page.evaluate("window.__report");await page.screenshot({path:shot});await browser.close();
let pass=true;const check=(n,ok,d="")=>{console.log((ok?"PASS ":"FAIL ")+n+(d?`  [${d}]`:""));if(!ok)pass=false},uniq=a=>new Set(a.filter(n=>n&&n!=="none"));check("pageerrors 0",errors.length===0,errors.join(" | ").slice(0,260));check("all nine quarterback phases render",report.actors===9,`count=${report.actors}`);check("all nine body mechanics differ",uniq(report.shell).size===9,report.shell.join(","));check("quick, three and five-step feet differ",uniq(report.dropFeet).size===6,report.dropFeet.join(","));check("hitch replaces retreat cadence",uniq(report.hitchFeet).size===2,report.hitchFeet.join(","));check("snap and mesh use different ball security",uniq(report.snapHands).size>=1&&uniq(report.meshHands).size>=1&&[...uniq(report.snapHands)].every(n=>!uniq(report.meshHands).has(n)));check("arm load and follow-through differ",uniq(report.load).size>=1&&uniq(report.follow).size>=2&&[...uniq(report.load)].every(n=>!uniq(report.follow).has(n)));check("follow-through keeps the throw pose",report.followPose!=="none");console.log("shot: "+shot);process.exit(pass?0:1);
