// M15 end-to-end special-teams gate: calls a real punt in Play Now.
// Usage: node tools/special_teams_live_probe.mjs <built.html> [shot.png]
import { chromium } from "playwright";
const target=process.argv[2],shot=process.argv[3]||"_special-teams-live.png";
if(!target){console.error("usage: node tools/special_teams_live_probe.mjs <built.html> [shot.png]");process.exit(1)}
const browser=await chromium.launch({executablePath:process.env.PW_CHROMIUM||undefined}),page=await browser.newPage({viewport:{width:1180,height:820}}),errors=[];page.on("pageerror",e=>errors.push(String(e)));await page.goto("file://"+target,{waitUntil:"load"});await page.waitForTimeout(700);await page.click("#btn-mm-playnow");await page.waitForTimeout(450);await page.click('[data-pn-star="home:3"]');await page.click('[data-pn-div="away:D3"]');await page.waitForTimeout(220);await page.click('[data-pn-star="away:3"]');await page.waitForTimeout(220);await page.click("#pn-start");
let sheet=false;
for(let i=0;i<100;i++){if(await page.locator('[data-cs-st-toggle]').count()){sheet=true;break}for(const s of['#dc-ride','#dc-send','#watch-live-skip','#watch-continue']){const n=page.locator(s);if(await n.count())await n.click().catch(()=>{})}await page.waitForTimeout(250)}
if(sheet){await page.click('[data-cs-st-toggle]');await page.waitForTimeout(80);await page.click('[data-cs-st="punt"]')}
let board=false,approach=false,plant=false,contact=false,follow=false,flight=false,landing=false,track=false,secure=false,cover=false,shotDone=false,leaked=false;
for(let frame=0;frame<520;frame++){const s=await page.evaluate(()=>{const b=document.querySelector("#watch-board"),ball=b?.querySelector("#wp-ball");return{board:!!b?.classList.contains("watch-kick-punt"),approach:!!b?.querySelector(".wp-kick-approach"),plant:!!b?.querySelector(".wp-kick-plant"),contact:!!b?.querySelector(".wp-kick-contact"),follow:!!b?.querySelector(".wp-kick-follow"),flight:!!ball?.classList.contains("wp-ball-punt"),landing:!!b?.querySelector(".wp-kick-landing-live"),track:!!b?.querySelector(".wp-return-track"),secure:!!b?.querySelector(".wp-return-secure"),inPlay:!!b?.classList.contains("watch-in-play")}});board||=s.board;approach||=s.approach;plant||=s.plant;contact||=s.contact;follow||=s.follow;flight||=s.flight;landing||=s.landing;track||=s.track;secure||=s.secure;if(!shotDone&&s.flight&&s.track){await page.screenshot({path:shot});shotDone=true}if(board&&!s.inPlay&&s.approach)leaked=true;if(board&&follow&&flight&&secure)break;await page.waitForTimeout(12)}if(!shotDone)await page.screenshot({path:shot});await browser.close();let pass=true;const check=(n,ok,d="")=>{console.log((ok?"PASS ":"FAIL ")+n+(d?`  [${d}]`:""));if(!ok)pass=false};check("pageerrors 0",errors.length===0,errors.join(" | ").slice(0,260));check("offensive call sheet reached",sheet);check("real Play Now punt uses M15 board",board);check("punter moves through approach, plant, contact and follow",approach&&plant&&contact&&follow,`approach=${approach} plant=${plant} contact=${contact} follow=${follow}`);check("punt flight and landing read appear",flight&&landing,`flight=${flight} landing=${landing}`);check("returner tracks and secures the live ball",track&&secure,`track=${track} secure=${secure}`);check("kick phases do not leak before the play",!leaked);console.log("shot: "+shot);process.exit(pass?0:1);
