// M15 special-teams mechanics gallery and structural visual gate.
// Usage: node tools/special_teams_probe.mjs [shot.png]
import { execFileSync } from "node:child_process";
import { readFileSync,writeFileSync,mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join,dirname } from "node:path";
import { fileURLToPath,pathToFileURL } from "node:url";
const root=join(dirname(fileURLToPath(import.meta.url)),".."),shot=process.argv[2]||join(root,"_special-teams.png"),tmp=mkdtempSync(join(tmpdir(),"wspst-")),entry=join(tmp,"entry.js"),bundle=join(tmp,"bundle.js");
writeFileSync(entry,`import { spriteMarkup,ballMarkup } from ${JSON.stringify(join(root,"js/ui/sprite.js").replace(/\\/g,"/"))};window.__spriteMarkup=spriteMarkup;window.__ballMarkup=ballMarkup;`);
const esbuild=process.platform==="win32"?join(root,"node_modules/@esbuild/win32-x64/esbuild.exe"):join(root,"node_modules/esbuild/bin/esbuild");
execFileSync(esbuild,[entry,"--bundle","--format=iife",`--outfile=${bundle}`],{stdio:"pipe"});
const css=readFileSync(join(root,"style.css"),"utf8"),js=readFileSync(bundle,"utf8");
const html=`<!doctype html><meta charset="utf-8"><style>${css}html,body{margin:0;background:#061b16}#watch-board{display:block;width:1600px;height:1000px}.st-title{fill:#ffd34d;font:900 2px monospace;text-anchor:middle}.st-sub{fill:#a9c0b2;font:800 .82px monospace;text-anchor:middle}.st-rule{stroke:#214b36;stroke-width:.18}.st-cell .wsp-tag{display:none}</style><svg id="watch-board" class="watch-sprites watch-in-play watch-special-teams watch-kick-place watch-kick-punt watch-kickoff" viewBox="0 0 200 125"></svg><script>${js}<\/script><script>
const svg=document.getElementById('watch-board');svg.style.setProperty('--wsp-off','#f1ead8');svg.style.setProperty('--wsp-off-hl','#d9a719');svg.style.setProperty('--wsp-def','#8b2942');svg.style.setProperty('--wsp-def-hl','#f1ead8');
const actor=(team,id,pos,face,cls,x,y)=>'<g class="st-cell wp-actor wp-team-'+team+' wsp-still wsp-face-'+face+' '+cls+'" data-case="'+id+'" transform="translate('+x+','+y+') scale(4)">'+window.__spriteMarkup({id:team+'-'+id,team,label:pos,pos,grp:pos},face)+'</g>';
const cases=[['APPROACH','off','K','wp-kick-approach'],['PLANT','off','K','wp-kick-plant'],['CONTACT','off','K','wp-kick-contact'],['FOLLOW','off','K','wp-kick-follow'],['PUNT GATHER','off','P','wp-kick-gather'],['HOLDER PLACE','off','H','wp-hold-place'],['TRACK','def','PR','wp-return-track'],['SECURE','def','PR','wp-return-secure'],['RETURN BURST','def','PR','wp-return-burst'],['COVER LANE','off','CV','wp-cover-lane']];let out='<line class="st-rule" x1="4" x2="196" y1="62" y2="62"/>';
cases.forEach((c,i)=>{const top=i<5,col=i%5,x=20+col*40,y=top?50:113;out+='<text class="st-title" x="'+x+'" y="'+(top?7:69)+'">'+c[0]+'</text><text class="st-sub" x="'+x+'" y="'+(top?9.5:71.5)+'">'+(top?'KICK CHAIN':'BALL / COVER')+'</text>'+actor(c[1],'case-'+i,c[2],i%2?'w':'e',c[3],x,y)});
out+='<g data-ball="kick" class="wp-ball-kick wp-ball-kickoff" transform="translate(181,16) scale(3)">'+window.__ballMarkup(0,0).replace('id="wp-ball"','id="probe-ball"').replace('class="wa-ballg"','class="wa-ballg wp-ball-kick wp-ball-kickoff"')+'</g><g class="wp-kick-landing wp-kick-landing-live" transform="translate(181,26)"><ellipse rx="2.7" ry="1.05"/><ellipse rx="1.55" ry=".6"/><path d="M0-1.65v3.3M-1.1-.85L0-1.65l1.1.8"/></g>';svg.innerHTML=out;
const anim=n=>n?getComputedStyle(n).animationName:'missing',display=n=>n?getComputedStyle(n).display:'missing',nodes=[...svg.querySelectorAll('[data-case]')];window.__report={actors:nodes.length,shell:nodes.map(n=>anim(n.querySelector('.wsp-shell'))),plantLeg:anim(nodes[1].querySelector('.wsp-sd-thigh-f')),contactLeg:anim(nodes[2].querySelector('.wsp-sd-thigh-b')),followLeg:anim(nodes[3].querySelector('.wsp-sd-thigh-b')),gather:display(nodes[4].querySelector('.wsp-pose-carry')),holder:display(nodes[5].querySelector('.wsp-pose-carry')),track:display(nodes[6].querySelector('.wsp-pose-catch')),secure:display(nodes[7].querySelector('.wsp-pose-carry')),burst:display(nodes[8].querySelector('.wsp-pose-carry')),landing:anim(svg.querySelector('.wp-kick-landing'))};
<\/script>`;
const pagePath=join(tmp,"special-teams.html");writeFileSync(pagePath,html);const {chromium}=await import(pathToFileURL(join(root,"node_modules/playwright/index.mjs")).href),browser=await chromium.launch({executablePath:process.env.PW_CHROMIUM||undefined}),page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];page.on("pageerror",e=>errors.push(String(e)));await page.goto("file://"+pagePath);await page.waitForTimeout(260);const report=await page.evaluate("window.__report");await page.screenshot({path:shot});await browser.close();let pass=true;const check=(n,ok,d="")=>{console.log((ok?"PASS ":"FAIL ")+n+(d?`  [${d}]`:""));if(!ok)pass=false},uniq=a=>new Set(a.filter(n=>n&&n!=="none"&&n!=="missing"));check("pageerrors 0",errors.length===0,errors.join(" | ").slice(0,260));check("all ten special-teams actors render",report.actors===10,`count=${report.actors}`);check("kick and return phases own distinct body mechanics",uniq(report.shell).size>=8,report.shell.join(","));check("plant, contact and follow use distinct kicking-leg frames",new Set([report.plantLeg,report.contactLeg,report.followLeg]).size===3,[report.plantLeg,report.contactLeg,report.followLeg].join(","));check("punt gathers ball before drop",report.gather==="block");check("holder pins the placement",report.holder==="block");check("returner tracks, secures and bursts",report.track==="block"&&report.secure==="block"&&report.burst==="block",[report.track,report.secure,report.burst].join(","));check("landing reticle pulses",report.landing==="wp-m15-landing",report.landing);console.log("shot: "+shot);process.exit(pass?0:1);
